### PR TITLE
Fix: underpriced tx handling & tx retries

### LINKED ISSUE #313: [BUG] Potential replacement transaction issue
Currently the contract calls cannot handle `Replacement Transaction underpriced`.

### PR DESCRIPTION
**Pull request by JannikSt**
fixes #313

### CODE REVIEW

File: crates/shared/src/web3/contracts/helpers/utils.rs [hunk 1]
```diff
@@ -1,5 +1,85 @@
...
 }
+
+pub type PrimeCallBuilder<'a> =
+    CallBuilder<Http<Client>, &'a WalletProvider, alloy::json_abi::Function, Ethereum>;
+pub async fn retry_call(
+    mut call: PrimeCallBuilder<'_>,
+    max_tries: u32,
+    initial_gas_price: Option<u128>,
+) -> Result<FixedBytes<32>, Box<dyn std::error::Error>> {
+    const WATCH_TIMEOUT_SECS: u64 = 20;
```
Comment (manveerxyz) [inline crates/shared/src/web3/contracts/helpers/utils.rs:22]: is there a chance 20s could be overly strict?

File: crates/shared/src/web3/contracts/helpers/utils.rs [hunk 2]
```diff
@@ -1,5 +1,85 @@
...
+                        if tries == max_tries {
+                            return Err("Max retries reached after watch timeouts".into());
+                        }
+                    }
+                }
+            }
+            Err(err) => {
+                if err
+                    .to_string()
+                    .contains("replacement transaction underpriced")
```
[the remark this answers is not in the document]
Comment (JannikSt) [reply crates/shared/src/web3/contracts/helpers/utils.rs:91]: thats handled automatically by the alloy-rs filler

File: crates/shared/src/web3/contracts/helpers/utils.rs (hunk 1 above)
Comment (JannikSt) [reply crates/shared/src/web3/contracts/helpers/utils.rs:26]: usually not with a blocktime of 2s - additionally a transaction that is resend will increase the gas and should cause the transaction to be part of the next block earlier
